version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - '3000:3000'
    env_file: ../.env.local
    environment:
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - api

  provider:
    build:
      context: ..
      dockerfile: docker/provider.Dockerfile
    ports:
      - '3001:3001'
    env_file: ../.env.local
    environment:
      NEXTAUTH_URL: http://localhost:3001
    depends_on:
      - api

  employee:
    build:
      context: ..
      dockerfile: docker/employee.Dockerfile
    ports:
      - '3002:3002'
    env_file: ../.env.local
    environment:
      NEXTAUTH_URL: http://localhost:3002
    depends_on:
      - api

  admin:
    build:
      context: ..
      dockerfile: docker/admin.Dockerfile
    ports:
      - '3003:3003'
    env_file: ../.env.local
    environment:
      NEXTAUTH_URL: http://localhost:3003
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - '4000:4000'
    env_file: ../.env.local
    environment:
      DATABASE_URL: postgresql://orbya:password@postgres:5432/orbya
      REDIS_URL: redis://redis:6379
      MEILISEARCH_HOST: http://meilisearch:7700
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      meilisearch:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: orbya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orbya
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U orbya -d orbya']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.9
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY}
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
